python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0005/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0015/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0025/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0035/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0045/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0055/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0065/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0075/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0085/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.25Pout0.0095/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0005/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0015/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0025/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0035/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0045/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0055/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0065/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0075/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0085/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.5Pout0.0095/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0005/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0015/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0025/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0035/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0045/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0055/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0065/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0075/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0085/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C2Pin0.75Pout0.0095/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0005/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0015/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0025/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0035/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0045/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0055/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0065/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0075/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0085/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.25Pout0.0095/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0005/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0015/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0025/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0035/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0045/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0055/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0065/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0075/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0085/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.5Pout0.0095/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0005/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0015/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0025/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0035/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0045/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0055/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0065/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0075/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0085/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C4Pin0.75Pout0.0095/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0005/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0015/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0025/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0035/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0045/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0055/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0065/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0075/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0085/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.25Pout0.0095/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0005/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0015/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0025/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0035/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0045/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0055/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0065/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0075/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0085/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.5Pout0.0095/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0005/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0015/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0025/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0035/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0045/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0055/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0065/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0075/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0085/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10
python -m graphsage.unsupervised_train --train_prefix ./C8Pin0.75Pout0.0095/ppi --model graphsage_meanpool --max_total_steps 1000 --validate_iter 10